name: Build Password Generator AppImage

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install appimage-builder
        run: |
          wget https://github.com/AppImageCrafters/appimage-builder/releases/latest/download/appimage-builder-x86_64.AppImage
          chmod +x appimage-builder-x86_64.AppImage

      - name: Build AppImage
        run: |
          ./appimage-builder-x86_64.AppImage --recipe appimage-builder.yml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PasswordGenerator.AppImage
          path: ./PasswordGenerator-x86_64.AppImage
